### ISSUE TITLE
Bug in transliteration with double-letters

### ISSUE THREAD

**Issue by majkinetor** [dalibor/cyrillizer#12]
I think you should sort the hash over the length:

	 def to_cyr
	      a=alphabet.invert.sort_by{ |k,v| k.length }.reverse.to_h
	      code(self.dup,a)
	 end

Currently it happens that for instance `nj` get translaterated as `нј` instead of `њ` because`j` comes before it in the alphabet hash and it gets replaced by the same looking but different character, such as this:

	from = "j"
	 bytes = Array (1 element)
	  [0] = 106
	to = "ј"
	 bytes = Array (2 elements)
	  [0] = 209
	  [1] = 152

after which `gsub('nj'..)` doesn't produce anything.

Sorting the array differently gets rid of this problem.

**Comment by majkinetor** [comment]
Seems that only 'j' is the problem and easier solution would be to move it in the alphabet bellow 'nj' and 'lj'.

**Comment by dalibor** [comment]
@majkinetor Thanks for the idea.
