### ISSUE TITLE
Error translating combination "ля" in word "для". Now: "dlя", expected: "dlya"

### ISSUE THREAD

**Issue by krdprog** [dalibor/cyrillizer#14]
Error translating combination "ля" in word "для". Now: "dlя", expected: "dlya"

**Comment by dalibor** [comment]
Hi @krdprog! You can provide a custom alphabet:

```ruby
Cyrillizer.alphabet = "alphabet/russian.yml" # path to the alphabet
```

Or, please provide a patch for the current Russian alphabet, I'm not familiar with it. Thanks!

**Comment by dalibor** [comment]
Closing this one. If the alphabet needs fixing, please provide a PR.
